"""
Auto-generated by bootstrap-rktio-pycket.rkt using rktio.rktl
Modifying by hand is not recommended.


Defines and provides some struct pointer types, and three list of tuples:

DEFINE_FUNCTION =
  [(rffi-(return)-type, func-name, [(rffi-type arg-name) ...]]

DEFINE_FUNCTION_ERRNO & DEFINE_FUNCTION_ERRNO_STEP =
  [(rffi-err-val, rffi-(return)-type, func-name, [(rffi-type arg-name) ...]

As well as a map of names for struct pointers to rffi and Pycket types.
We use the map to generate pointer types for rffi and Pycket wrappers to
use when passing stuff around.

We use the tuples (in pycket/rktio.py) to auto-generete the
rffi.llexternal calls, as well as the functions exposed to the
Pycket runtime (@expose_with_rffi) to call these.

"""



from pycket.rktio.common import *

bootstrap_struct_type("dll_open_proc", ("DLL_OPEN_PROC_PTR", "W_DLL_OPEN_PROC_PTR")
bootstrap_struct_type("rktio_fs_change_t", ("RKTIO_FS_CHANGE_T_PTR", "W_RKTIO_FS_CHANGE_T_PTR")
bootstrap_struct_type("rktio_sha1_ctx_t", ("RKTIO_SHA1_CTX_T_PTR", "W_RKTIO_SHA1_CTX_T_PTR")
bootstrap_struct_type("rktio_stat_t", ("RKTIO_STAT_T_PTR", "W_RKTIO_STAT_T_PTR")
bootstrap_struct_type("rktio_addrinfo_lookup_t", ("RKTIO_ADDRINFO_LOOKUP_T_PTR", "W_RKTIO_ADDRINFO_LOOKUP_T_PTR")
bootstrap_struct_type("rktio_envvars_t", ("RKTIO_ENVVARS_T_PTR", "W_RKTIO_ENVVARS_T_PTR")
bootstrap_struct_type("rktio_length_and_addrinfo_t", ("RKTIO_LENGTH_AND_ADDRINFO_T_PTR", "W_RKTIO_LENGTH_AND_ADDRINFO_T_PTR")
bootstrap_struct_type("rktio_fd_t", ("RKTIO_FD_T_PTR", "W_RKTIO_FD_T_PTR")
bootstrap_struct_type("rktio_file_copy_t", ("RKTIO_FILE_COPY_T_PTR", "W_RKTIO_FILE_COPY_T_PTR")
bootstrap_struct_type("rktio_signal_handle_t", ("RKTIO_SIGNAL_HANDLE_T_PTR", "W_RKTIO_SIGNAL_HANDLE_T_PTR")
bootstrap_struct_type("rktio_connect_t", ("RKTIO_CONNECT_T_PTR", "W_RKTIO_CONNECT_T_PTR")
bootstrap_struct_type("rktio_ltps_handle_t", ("RKTIO_LTPS_HANDLE_T_PTR", "W_RKTIO_LTPS_HANDLE_T_PTR")
bootstrap_struct_type("rktio_dll_t", ("RKTIO_DLL_T_PTR", "W_RKTIO_DLL_T_PTR")
bootstrap_struct_type("rktio_date_t", ("RKTIO_DATE_T_PTR", "W_RKTIO_DATE_T_PTR")
bootstrap_struct_type("rktio_process_t", ("RKTIO_PROCESS_T_PTR", "W_RKTIO_PROCESS_T_PTR")
bootstrap_struct_type("rktio_ltps_t", ("RKTIO_LTPS_T_PTR", "W_RKTIO_LTPS_T_PTR")
bootstrap_struct_type("rktio_sha2_ctx_t", ("RKTIO_SHA2_CTX_T_PTR", "W_RKTIO_SHA2_CTX_T_PTR")
bootstrap_struct_type("rktio_t", ("RKTIO_T_PTR", "W_RKTIO_T_PTR")
bootstrap_struct_type("rktio_identity_t", ("RKTIO_IDENTITY_T_PTR", "W_RKTIO_IDENTITY_T_PTR")
bootstrap_struct_type("rktio_poll_set_t", ("RKTIO_POLL_SET_T_PTR", "W_RKTIO_POLL_SET_T_PTR")
bootstrap_struct_type("rktio_converter_t", ("RKTIO_CONVERTER_T_PTR", "W_RKTIO_CONVERTER_T_PTR")
bootstrap_struct_type("rktio_convert_result_t", ("RKTIO_CONVERT_RESULT_T_PTR", "W_RKTIO_CONVERT_RESULT_T_PTR")
bootstrap_struct_type("rktio_fd_transfer_t", ("RKTIO_FD_TRANSFER_T_PTR", "W_RKTIO_FD_TRANSFER_T_PTR")
bootstrap_struct_type("rktio_status_t", ("RKTIO_STATUS_T_PTR", "W_RKTIO_STATUS_T_PTR")
bootstrap_struct_type("dll_close_proc", ("DLL_CLOSE_PROC_PTR", "W_DLL_CLOSE_PROC_PTR")
bootstrap_struct_type("rktio_listener_t", ("RKTIO_LISTENER_T_PTR", "W_RKTIO_LISTENER_T_PTR")
bootstrap_struct_type("rktio_addrinfo_t", ("RKTIO_ADDRINFO_T_PTR", "W_RKTIO_ADDRINFO_T_PTR")
bootstrap_struct_type("rktio_process_result_t", ("RKTIO_PROCESS_RESULT_T_PTR", "W_RKTIO_PROCESS_RESULT_T_PTR")
bootstrap_struct_type("dll_find_object_proc", ("DLL_FIND_OBJECT_PROC_PTR", "W_DLL_FIND_OBJECT_PROC_PTR")
bootstrap_struct_type("rktio_directory_list_t", ("RKTIO_DIRECTORY_LIST_T_PTR", "W_RKTIO_DIRECTORY_LIST_T_PTR")


DEFINE_FUNCTION = [

    (CCHARP, "rktio_get_error_string", [(RKTIO_T_PTR, "rktio"),(INT, "kind"),(INT, "errid")]),
    (CCHARP, "rktio_get_last_error_string", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_remap_last_error", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_set_last_error_step", [(RKTIO_T_PTR, "rktio"),(INT, "step")]),
    (VOID, "rktio_set_last_error", [(RKTIO_T_PTR, "rktio"),(INT, "kind"),(INT, "errid")]),
    (INT, "rktio_get_last_error_step", [(RKTIO_T_PTR, "rktio")]),
    (INT, "rktio_get_last_error", [(RKTIO_T_PTR, "rktio")]),
    (INT, "rktio_get_last_error_kind", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_set_dll_procs", [(DLL_OPEN_PROC_PTR, "dll_open"),(DLL_FIND_OBJECT_PROC_PTR, "dll_find_object"),(DLL_CLOSE_PROC_PTR, "dll_close")]),
    (VOID, "rktio_sha2_final", [(RKTIO_SHA2_CTX_T_PTR, "ctx"),(UNSIGNED_8, "digest")]),
    (VOID, "rktio_sha2_update", [(RKTIO_SHA2_CTX_T_PTR, "ctx"),(UNSIGNED_8, "data"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (VOID, "rktio_sha2_init", [(RKTIO_SHA2_CTX_T_PTR, "ctx"),(RKTIO_BOOL_T, "is224")]),
    (VOID, "rktio_sha1_final", [(RKTIO_SHA1_CTX_T_PTR, "context"),(UNSIGNED_8, "digest")]),
    (VOID, "rktio_sha1_update", [(RKTIO_SHA1_CTX_T_PTR, "context"),(UNSIGNED_8, "data"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (VOID, "rktio_sha1_init", [(RKTIO_SHA1_CTX_T_PTR, "context")]),
    (VOID, "rktio_pop_c_numeric_locale", [(RKTIO_T_PTR, "rktio"),(VOID, "prev")]),
    (VOID, "rktio_push_c_numeric_locale", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_set_default_locale", [(RKTIO_CONST_STRING_T, "name")]),
    (VOID, "rktio_set_locale", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "name")]),
    (INT, "rktio_strcoll_utf16", [(RKTIO_T_PTR, "rktio"),(RKTIO_CHAR16_T, "s1"),(INTPTR_T, "l1"),(RKTIO_CHAR16_T, "s2"),(INTPTR_T, "l2"),(RKTIO_BOOL_T, "cvt_case")]),
    (INT, "rktio_locale_strcoll", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "s1"),(RKTIO_CONST_STRING_T, "s2")]),
    (RKTIO_CHAR16_T, "rktio_recase_utf16", [(RKTIO_T_PTR, "rktio"),(RKTIO_BOOL_T, "to_up"),(RKTIO_CHAR16_T, "s1"),(INTPTR_T, "len"),(INTPTR_T, "olen")]),
    (CCHARP, "rktio_locale_recase", [(RKTIO_T_PTR, "rktio"),(RKTIO_BOOL_T, "to_up"),(RKTIO_CONST_STRING_T, "in")]),
    (VOID, "rktio_convert_reset", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONVERTER_T_PTR, "cvt")]),
    (VOID, "rktio_converter_close", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONVERTER_T_PTR, "cvt")]),
    (INT, "rktio_convert_properties", [(RKTIO_T_PTR, "rktio")]),
    (INT, "rktio_processor_count", [(RKTIO_T_PTR, "rktio")]),
    (CCHARP, "rktio_wide_path_to_path", [(RKTIO_T_PTR, "rktio"),(RKTIO_CHAR16_T, "wp")]),
    (RKTIO_TIMESTAMP_T, "rktio_get_seconds", [(RKTIO_T_PTR, "rktio")]),
    (UINTPTR_T, "rktio_get_process_children_milliseconds", [(RKTIO_T_PTR, "rktio")]),
    (UINTPTR_T, "rktio_get_process_milliseconds", [(RKTIO_T_PTR, "rktio")]),
    (DOUBLE, "rktio_get_inexact_monotonic_milliseconds", [(RKTIO_T_PTR, "rktio")]),
    (DOUBLE, "rktio_get_inexact_milliseconds", []),
    (UINTPTR_T, "rktio_get_milliseconds", []),
    (VOID, "rktio_will_modify_os_signal_handler", [(INT, "sig_id")]),
    (INT, "rktio_poll_os_signal", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_install_os_signal_handler", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_flush_signals_received", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_wait_until_signal_received", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_signal_received", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_signal_received_at", [(RKTIO_SIGNAL_HANDLE_T_PTR, "h")]),
    (RKTIO_SIGNAL_HANDLE_T_PTR, "rktio_get_signal_handle", [(RKTIO_T_PTR, "rktio")]),
    (CCHARP, "rktio_uname", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_copy_file_stop", [(RKTIO_T_PTR, "rktio"),(RKTIO_FILE_COPY_T_PTR, "fc")]),
    (RKTIO_BOOL_T, "rktio_copy_file_is_done", [(RKTIO_T_PTR, "rktio"),(RKTIO_FILE_COPY_T_PTR, "fc")]),
    (VOID, "rktio_directory_list_stop", [(RKTIO_T_PTR, "rktio"),(RKTIO_DIRECTORY_LIST_T_PTR, "dl")]),
    (RKTIO_BOOL_T, "rktio_is_regular_file", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (RKTIO_BOOL_T, "rktio_link_exists", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (RKTIO_BOOL_T, "rktio_directory_exists", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "dirname")]),
    (RKTIO_BOOL_T, "rktio_file_exists", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (VOID, "rktio_end_sleep", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_sleep", [(RKTIO_T_PTR, "rktio"),(FLOAT, "nsecs"),(RKTIO_POLL_SET_T_PTR, "fds"),(RKTIO_LTPS_T_PTR, "lt")]),
    (VOID, "rktio_ltps_handle_set_auto", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_HANDLE_T_PTR, "lth"),(INT, "auto_mode")]),
    (VOID, "rktio_ltps_remove_all", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_T_PTR, "lt")]),
    (VOID, "rktio_ltps_handle_get_data", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_HANDLE_T_PTR, "h")]),
    (VOID, "rktio_ltps_handle_set_data", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_HANDLE_T_PTR, "h"),(VOID, "data")]),
    (VOID, "rktio_ltps_close", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_T_PTR, "lt")]),
    (VOID, "rkio_reset_sleep_backoff", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_poll_set_add_eventmask", [(RKTIO_T_PTR, "rktio"),(RKTIO_POLL_SET_T_PTR, "fds"),(INT, "mask")]),
    (VOID, "rktio_poll_set_add_handle", [(RKTIO_T_PTR, "rktio"),(INTPTR_T, "h"),(RKTIO_POLL_SET_T_PTR, "fds"),(INT, "repost")]),
    (VOID, "rktio_poll_set_add_nosleep", [(RKTIO_T_PTR, "rktio"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add_fs_change", [(RKTIO_T_PTR, "rktio"),(RKTIO_FS_CHANGE_T_PTR, "fc"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add_process", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add_addrinfo_lookup", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_LOOKUP_T_PTR, "lookup"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add_connect", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONNECT_T_PTR, "conn"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add_accept", [(RKTIO_T_PTR, "rktio"),(RKTIO_LISTENER_T_PTR, "listener"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_poll_add", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_POLL_SET_T_PTR, "fds"),(INT, "modes")]),
    (VOID, "rktio_poll_set_forget", [(RKTIO_T_PTR, "rktio"),(RKTIO_POLL_SET_T_PTR, "fds")]),
    (VOID, "rktio_fs_change_forget", [(RKTIO_T_PTR, "rktio"),(RKTIO_FS_CHANGE_T_PTR, "fc")]),
    (INT, "rktio_fs_change_properties", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_reap_processes", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_process_forget", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (INT, "rktio_process_pid", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (INT, "rktio_process_allowed_flags", [(RKTIO_T_PTR, "rktio")]),
    (INTPTR_T, "rktio_envvars_count", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars")]),
    (VOID, "rktio_envvars_set", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars"),(RKTIO_CONST_STRING_T, "name"),(RKTIO_CONST_STRING_T, "value")]),
    (VOID, "rktio_envvars_free", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars")]),
    (RKTIO_BOOL_T, "rktio_are_envvar_names_case_insensitive", [(RKTIO_T_PTR, "rktio")]),
    (RKTIO_BOOL_T, "rktio_is_ok_envvar_name", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "name")]),
    (VOID, "rktio_connect_stop", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONNECT_T_PTR, "conn")]),
    (VOID, "rktio_listen_stop", [(RKTIO_T_PTR, "rktio"),(RKTIO_LISTENER_T_PTR, "l")]),
    (VOID, "rktio_addrinfo_free", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_T_PTR, "a")]),
    (VOID, "rktio_addrinfo_lookup_stop", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_LOOKUP_T_PTR, "lookup")]),
    (INT, "rktio_get_ipv4_family", [(RKTIO_T_PTR, "rktio")]),
    (VOID, "rktio_fd_close_transfer", [(RKTIO_FD_TRANSFER_T_PTR, "rfdt")]),
    (RKTIO_FD_T_PTR, "rktio_fd_attach", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_TRANSFER_T_PTR, "rfdt")]),
    (RKTIO_FD_TRANSFER_T_PTR, "rktio_fd_detach", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (INTPTR_T, "rktio_buffered_byte_count", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (VOID, "rktio_create_console", []),
    (VOID, "rktio_forget", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (VOID, "rktio_close_noerr", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (INT, "rktio_fd_modes", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_pending_open", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_text_converted", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_terminal", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_udp", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_socket", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_directory", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_BOOL_T, "rktio_fd_is_regular_file", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (INTPTR_T, "rktio_fd_system_fd", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (VOID, "rktio_set_dll_path", [(RKTIO_CHAR16_T, "p")]),
    (VOID, "rktio_free", [(VOID, "p")]),
    (VOID, "rktio_destroy", [(RKTIO_T_PTR, "rktio")]),
    (RKTIO_T_PTR, "rktio_init", [])
]

DEFINE_FUNCTION_ERRNO = [

    (NULL, CCHARP, "rktio_dll_get_error", [(RKTIO_T_PTR, "rktio")]),
    (W_FALSE, RKTIO_OK_T, "rktio_dll_close", [(RKTIO_T_PTR, "rktio"),(RKTIO_DLL_T_PTR, "dll")]),
    (NULL, VOID, "rktio_dll_find_object", [(RKTIO_T_PTR, "rktio"),(RKTIO_DLL_T_PTR, "dll"),(RKTIO_CONST_STRING_T, "name")]),
    (NULL, RKTIO_DLL_T_PTR, "rktio_dll_open", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "name"),(RKTIO_BOOL_T, "as_global")]),
    (NULL, CCHARP, "rktio_system_language_country", [(RKTIO_T_PTR, "rktio")]),
    (NULL, CCHARP, "rktio_locale_encoding", [(RKTIO_T_PTR, "rktio")]),
    (NULL, RKTIO_CONVERT_RESULT_T_PTR, "rktio_convert_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONVERTER_T_PTR, "cvt"),(CCHARP, "in"),(INTPTR_T, "in_start"),(INTPTR_T, "in_end"),(CCHARP, "out"),(INTPTR_T, "out_start"),(INTPTR_T, "out_end")]),
    (RKTIO_CONVERT_ERROR, INTPTR_T, "rktio_convert", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONVERTER_T_PTR, "cvt"),(CCHARPP, "in"),(INTPTR_T, "in_left"),(CCHARPP, "out"),(INTPTR_T, "out_left")]),
    (NULL, RKTIO_CONVERTER_T_PTR, "rktio_converter_open", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "to_enc"),(RKTIO_CONST_STRING_T, "from_enc")]),
    (W_FALSE, RKTIO_OK_T, "rktio_syslog", [(RKTIO_T_PTR, "rktio"),(INT, "level"),(RKTIO_CONST_STRING_T, "name"),(RKTIO_CONST_STRING_T, "msg"),(RKTIO_CONST_STRING_T, "exec_name")]),
    (NULL, RKTIO_CHAR16_T, "rktio_path_to_wide_path", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "p")]),
    (W_FALSE, RKTIO_OK_T, "rktio_shell_execute", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "verb"),(RKTIO_CONST_STRING_T, "target"),(RKTIO_CONST_STRING_T, "arg"),(RKTIO_CONST_STRING_T, "dir"),(INT, "show_mode")]),
    (NULL, RKTIO_DATE_T_PTR, "rktio_seconds_to_date", [(RKTIO_T_PTR, "rktio"),(RKTIO_TIMESTAMP_T, "seconds"),(INT, "nanoseconds"),(INT, "get_gmt")]),
    (NULL, CCHARP, "rktio_expand_user_tilde", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (NULL, CCHARP, "rktio_system_path", [(RKTIO_T_PTR, "rktio"),(INT, "which")]),
    (NULL, CCHARPP, "rktio_filesystem_roots", [(RKTIO_T_PTR, "rktio")]),
    (NULL, CCHARP, "rktio_directory_list_step", [(RKTIO_T_PTR, "rktio"),(RKTIO_DIRECTORY_LIST_T_PTR, "dl")]),
    (NULL, RKTIO_DIRECTORY_LIST_T_PTR, "rktio_directory_list_start", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "dirname")]),
    (W_FALSE, RKTIO_OK_T, "rktio_set_file_or_directory_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename"),(INT, "new_bits")]),
    (RKTIO_PERMISSION_ERROR, INT, "rktio_get_file_or_directory_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename"),(RKTIO_BOOL_T, "all_bits")]),
    (NULL, RKTIO_IDENTITY_T_PTR, "rktio_path_identity", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "path"),(RKTIO_BOOL_T, "follow_links")]),
    (NULL, RKTIO_IDENTITY_T_PTR, "rktio_fd_identity", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (NULL, RKTIO_STAT_T_PTR, "rktio_fd_stat", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (NULL, RKTIO_STAT_T_PTR, "rktio_file_or_directory_stat", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "path"),(RKTIO_BOOL_T, "follow_links")]),
    (W_FALSE, RKTIO_OK_T, "rktio_set_file_modify_seconds", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "file"),(RKTIO_TIMESTAMP_T, "secs")]),
    (NULL, RKTIO_TIMESTAMP_T, "rktio_get_file_modify_seconds", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "file")]),
    (NULL, RKTIO_FILESIZE_T, "rktio_file_size", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (W_FALSE, RKTIO_OK_T, "rktio_make_link", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "src"),(RKTIO_CONST_STRING_T, "dest"),(RKTIO_BOOL_T, "dest_is_directory")]),
    (NULL, CCHARP, "rktio_readlink", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "fullfilename")]),
    (W_FALSE, RKTIO_OK_T, "rktio_delete_directory", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename"),(RKTIO_CONST_STRING_T, "current_directory"),(RKTIO_BOOL_T, "enable_write_on_fail")]),
    (W_FALSE, RKTIO_OK_T, "rktio_make_directory_with_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename"),(INT, "perm_bits")]),
    (W_FALSE, RKTIO_OK_T, "rktio_make_directory", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (W_FALSE, RKTIO_OK_T, "rktio_set_current_directory", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "path")]),
    (NULL, CCHARP, "rktio_get_current_directory", [(RKTIO_T_PTR, "rktio")]),
    (W_FALSE, RKTIO_OK_T, "rktio_rename_file", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "dest"),(RKTIO_CONST_STRING_T, "src"),(RKTIO_BOOL_T, "exists_ok")]),
    (W_FALSE, RKTIO_OK_T, "rktio_delete_file", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "fn"),(RKTIO_BOOL_T, "enable_write_on_fail")]),
    (RKTIO_FILE_TYPE_ERROR, INT, "rktio_file_type", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "filename")]),
    (W_FALSE, RKTIO_OK_T, "rktio_start_sleep", [(RKTIO_T_PTR, "rktio"),(FLOAT, "nsecs"),(RKTIO_POLL_SET_T_PTR, "fds"),(RKTIO_LTPS_T_PTR, "lt"),(INT, "woke_fd")]),
    (NULL, RKTIO_LTPS_HANDLE_T_PTR, "rktio_ltps_get_signaled_handle", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_T_PTR, "lt")]),
    (W_FALSE, RKTIO_OK_T, "rktio_ltps_poll", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_T_PTR, "lt")]),
    (NULL, RKTIO_LTPS_HANDLE_T_PTR, "rktio_ltps_add", [(RKTIO_T_PTR, "rktio"),(RKTIO_LTPS_T_PTR, "lt"),(RKTIO_FD_T_PTR, "rfd"),(INT, "mode")]),
    (NULL, RKTIO_LTPS_T_PTR, "rktio_ltps_open", [(RKTIO_T_PTR, "rktio")]),
    (NULL, RKTIO_POLL_SET_T_PTR, "rktio_make_poll_set", [(RKTIO_T_PTR, "rktio")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_fs_change_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_FS_CHANGE_T_PTR, "fc")]),
    (NULL, RKTIO_FS_CHANGE_T_PTR, "rktio_fs_change", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "path"),(RKTIO_LTPS_T_PTR, "ltps")]),
    (NULL, RKTIO_STATUS_T_PTR, "rktio_process_status", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (RKTIO_PROCESS_ERROR, RKTIO_TRI_T, "rktio_poll_process_done", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (W_FALSE, RKTIO_OK_T, "rktio_process_interrupt", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (W_FALSE, RKTIO_OK_T, "rktio_process_kill", [(RKTIO_T_PTR, "rktio"),(RKTIO_PROCESS_T_PTR, "sp")]),
    (NULL, RKTIO_PROCESS_RESULT_T_PTR, "rktio_process", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "command"),(INT, "argc"),(RKTIO_CONST_STRING_T, "argv"),(RKTIO_FD_T_PTR, "stdout_fd"),(RKTIO_FD_T_PTR, "stdin_fd"),(RKTIO_FD_T_PTR, "stderr_fd"),(RKTIO_PROCESS_T_PTR, "group_proc"),(RKTIO_CONST_STRING_T, "current_directory"),(RKTIO_ENVVARS_T_PTR, "envvars"),(INT, "flags")]),
    (NULL, CCHARP, "rktio_envvars_value_ref", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars"),(INTPTR_T, "i")]),
    (NULL, CCHARP, "rktio_envvars_name_ref", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars"),(INTPTR_T, "i")]),
    (NULL, CCHARP, "rktio_envvars_get", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars"),(RKTIO_CONST_STRING_T, "name")]),
    (NULL, RKTIO_ENVVARS_T_PTR, "rktio_envvars_copy", [(RKTIO_T_PTR, "rktio"),(RKTIO_ENVVARS_T_PTR, "envvars")]),
    (NULL, RKTIO_ENVVARS_T_PTR, "rktio_empty_envvars", [(RKTIO_T_PTR, "rktio")]),
    (NULL, RKTIO_ENVVARS_T_PTR, "rktio_envvars", [(RKTIO_T_PTR, "rktio")]),
    (W_FALSE, RKTIO_OK_T, "rktio_setenv", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "name"),(RKTIO_CONST_STRING_T, "val")]),
    (NULL, CCHARP, "rktio_getenv", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "name")]),
    (NULL, CCHARPP, "rktio_listener_address", [(RKTIO_T_PTR, "rktio"),(RKTIO_LISTENER_T_PTR, "lnr")]),
    (NULL, CCHARPP, "rktio_socket_peer_address", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (NULL, CCHARPP, "rktio_socket_address", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_change_multicast_group", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "group_addr"),(RKTIO_ADDRINFO_T_PTR, "intf_addr"),(INT, "action")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_set_multicast_interface", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "addr")]),
    (NULL, CCHARP, "rktio_udp_multicast_interface", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_set_multicast_ttl", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(INT, "ttl_val")]),
    (RKTIO_PROP_ERROR, RKTIO_TRI_T, "rktio_udp_get_multicast_ttl", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_set_multicast_loopback", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_BOOL_T, "on")]),
    (RKTIO_PROP_ERROR, RKTIO_TRI_T, "rktio_udp_get_multicast_loopback", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_PROP_ERROR, RKTIO_TRI_T, "rktio_udp_get_ttl", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_set_ttl", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(INT, "ttl_val")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_set_receive_buffer_size", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(INT, "size")]),
    (NULL, RKTIO_LENGTH_AND_ADDRINFO_T_PTR, "rktio_udp_recvfrom_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(CCHARP, "buffer"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (NULL, RKTIO_LENGTH_AND_ADDRINFO_T_PTR, "rktio_udp_recvfrom", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(CCHARP, "buffer"),(INTPTR_T, "len")]),
    (RKTIO_WRITE_ERROR, INTPTR_T, "rktio_udp_sendto_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "addr"),(CCHARP, "buffer"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (RKTIO_WRITE_ERROR, INTPTR_T, "rktio_udp_sendto", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "addr"),(CCHARP, "buffer"),(INTPTR_T, "len")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_connect", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "addr")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_bind", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_ADDRINFO_T_PTR, "addr"),(RKTIO_BOOL_T, "reuse")]),
    (W_FALSE, RKTIO_OK_T, "rktio_udp_disconnect", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_udp_open", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_T_PTR, "addr"),(INT, "family")]),
    (W_FALSE, RKTIO_OK_T, "rktio_tcp_nodelay", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_BOOL_T, "enable")]),
    (W_FALSE, RKTIO_OK_T, "rktio_socket_shutdown", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(INT, "mode")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_connect_trying", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONNECT_T_PTR, "conn")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_connect_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONNECT_T_PTR, "conn")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_connect_finish", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONNECT_T_PTR, "conn")]),
    (NULL, RKTIO_CONNECT_T_PTR, "rktio_start_connect", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_T_PTR, "remote"),(RKTIO_ADDRINFO_T_PTR, "local")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_accept", [(RKTIO_T_PTR, "rktio"),(RKTIO_LISTENER_T_PTR, "listener")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_accept_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_LISTENER_T_PTR, "listener")]),
    (NULL, RKTIO_LISTENER_T_PTR, "rktio_listen", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_T_PTR, "local"),(INT, "backlog"),(RKTIO_BOOL_T, "reuse")]),
    (NULL, RKTIO_ADDRINFO_T_PTR, "rktio_addrinfo_lookup_get", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_LOOKUP_T_PTR, "lookup")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_addrinfo_lookup_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_ADDRINFO_LOOKUP_T_PTR, "lookup")]),
    (NULL, RKTIO_ADDRINFO_LOOKUP_T_PTR, "rktio_start_addrinfo_lookup", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "hostname"),(INT, "portno"),(INT, "family"),(RKTIO_BOOL_T, "passive"),(RKTIO_BOOL_T, "tcp")]),
    (NULL, ARR_PTR(RKTIO_FD_T_PTR), "rktio_make_pipe", [(RKTIO_T_PTR, "rktio"),(INT, "flags")]),
    (W_FALSE, RKTIO_OK_T, "rktio_set_file_size", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_FILESIZE_T, "sz")]),
    (NULL, RKTIO_FILESIZE_T, "rktio_get_file_position", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_set_file_position", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_FILESIZE_T, "pos"),(INT, "whence")]),
    (W_FALSE, RKTIO_OK_T, "rktio_file_unlock", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_LOCK_ERROR, RKTIO_TRI_T, "rktio_file_lock_try", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd"),(RKTIO_BOOL_T, "excl")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_write_flushed", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_write_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_POLL_ERROR, RKTIO_TRI_T, "rktio_poll_read_ready", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (RKTIO_READ_ERROR, INTPTR_T, "rktio_read_converted_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "start"),(INTPTR_T, "len"),(CCHARP, "is_converted"),(INTPTR_T, "converted_start")]),
    (RKTIO_WRITE_ERROR, INTPTR_T, "rktio_write_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (RKTIO_READ_ERROR, INTPTR_T, "rktio_read_in", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "start"),(INTPTR_T, "end")]),
    (RKTIO_READ_ERROR, INTPTR_T, "rktio_read_converted", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "len"),(CCHARP, "is_converted")]),
    (RKTIO_WRITE_ERROR, INTPTR_T, "rktio_write", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "len")]),
    (RKTIO_READ_ERROR, INTPTR_T, "rktio_read", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd"),(CCHARP, "buffer"),(INTPTR_T, "len")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_std_fd", [(RKTIO_T_PTR, "rktio"),(INT, "which")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_dup", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "rfd")]),
    (W_FALSE, RKTIO_OK_T, "rktio_close", [(RKTIO_T_PTR, "rktio"),(RKTIO_FD_T_PTR, "fd")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_open_with_create_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "src"),(INT, "modes"),(INT, "perm_bits")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_open", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "src"),(INT, "modes")]),
    (NULL, RKTIO_FD_T_PTR, "rktio_system_fd", [(RKTIO_T_PTR, "rktio"),(INTPTR_T, "system_fd"),(INT, "modes")]),
    (NULL, RKTIO_CHAR16_T, "rktio_get_dll_path", [(RKTIO_CHAR16_T, "p")])
]

DEFINE_FUNCTION_ERRNO_STEP = [

    (W_FALSE, RKTIO_OK_T, "rktio_copy_file_finish_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_FILE_COPY_T_PTR, "fc")]),
    (W_FALSE, RKTIO_OK_T, "rktio_copy_file_step", [(RKTIO_T_PTR, "rktio"),(RKTIO_FILE_COPY_T_PTR, "fc")]),
    (NULL, RKTIO_FILE_COPY_T_PTR, "rktio_copy_file_start_permissions", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "dest"),(RKTIO_CONST_STRING_T, "src"),(RKTIO_BOOL_T, "exists_ok"),(RKTIO_BOOL_T, "use_perm_bits"),(INT, "perm_bits"),(RKTIO_BOOL_T, "override_create_perms")]),
    (NULL, RKTIO_FILE_COPY_T_PTR, "rktio_copy_file_start", [(RKTIO_T_PTR, "rktio"),(RKTIO_CONST_STRING_T, "dest"),(RKTIO_CONST_STRING_T, "src"),(RKTIO_BOOL_T, "exists_ok")])
]
