(module simpler-branchy '#%kernel

(#%provide function)

(define-values (function)
  (lambda (lst)
    ((letrec-values 
        ([(loop) 
          (lambda (lst)
            (if (null? lst)
                -1
                (let-values ([(index) (car lst)])
                  (if (< index 18)
                      (if (< index 8)
                          (if (< index 3)
                              (if (< index 1)
                                  (+ 1 (loop (cdr lst)))
                                  (if (< index 2)
                                      (loop (cdr lst))
                                      (loop (cdr lst))))
                              (if (< index 5)
                                  (if (< index 4)
                                      (+ 3 (loop (cdr lst)))
                                      (+ 5 (loop (cdr lst))))
                                  (if (< index 6)
                                      (loop (cdr lst))
                                      (if (< index 7)
                                          (loop (cdr lst))
                                          (loop (cdr lst))))))
                          (if (< index 12)
                              (if (< index 9)
                                  (loop (cdr lst))
                                  (if (< index 10)
                                      (+ 9 (loop (cdr lst)))
                                      (if (< index 11)
                                          (+ 10 (loop (cdr lst)))
                                          (loop (cdr lst)))))
                              (if (< index 14)
                                  (if (< index 13)
                                      (+ 12 (loop (cdr lst)))
                                      (+ 13.5 (loop (cdr lst))))
                                  (if (< index 15)
                                      (+ 14 (loop (cdr lst)))
                                      (if (< index 16)
                                          (+ 15 (loop (cdr lst)))
                                          (if (< index 17)
                                              (+ 15 (loop (cdr lst)))
                                              (+ 16 (loop (cdr lst)))))))))
                      (if (< index 27)
                          (if (< index 22)
                              (if (< index 19)
                                  (+ 18 (loop (cdr lst)))
                                  (if (< index 20)
                                      (+ 19 (string-length "imm") (loop (cdr lst)))
                                      (if (< index 21)
                                          (+ 20 (loop (cdr lst)))
                                          (+ 21 (loop (cdr lst))))))
                              (if (< index 24)
                                  (if (< index 23)
                                      (loop (cdr lst))
                                      (loop (cdr lst)))
                                  (if (< index 25)
                                      (+ 24 (loop (cdr lst)))
                                      (if (< index 26)
                                          (+ 25 (loop (cdr lst)))
                                          (+ 27 (loop (cdr lst)))))))
                          (if (< index 32)
                              (if (< index 29)
                                  (if (< index 28)
                                      (+ 27 (loop (cdr lst)))
                                      (+ 29 (loop (cdr lst))))
                                  (if (< index 30)
                                      (+ 1 (loop (cdr lst)))
                                      (if (< index 31)
                                          ((letrec-values (((ploop)
                                                            (lambda (len)
                                                              (if (zero? len)
                                                                  (+ 30.5 (loop (cdr lst)))
                                                                  (+ (ploop (sub1 len)))))))
                                             ploop)
                                           31)
                                          (loop (cdr lst)))))
                              (if (< index 34)
                                  (if (< index 33)
                                      (+ 32 (loop (cdr lst)))
                                      (+ 34 (loop (cdr lst))))
                                  (if (< index 35)
                                      (loop (cdr lst))
                                      (if (< index 36)
                                          (+ 35 (loop (cdr lst)))
                                          #;(let-values (((ht) (make-hasheq)))
                                              (let-values (((start) 0)
                                                           ((end) 36)
                                                           ((inc) 1))
                                                ((letrec-values (((for-loop)
                                                                  (lambda (pos)
                                                                    (if (< pos  end)
                                                                        (let-values (((j) pos))
                                                                          (let-values ((()
                                                                                        (let-values ()
                                                                                          (let-values ((()
                                                                                                        (let-values ()
                                                                                                          (let-values ()
                                                                                                            (hash-set! ht (loop (cdr lst)) (loop (cdr lst))))
                                                                                                          (values))))
                                                                                            (values)))))
                                                                            (for-loop (+ pos inc))))
                                                                        (values)))))
                                                   for-loop)
                                                 start))
                                              ht)
                                          (if (< index 37)
                                              (+ 36 (loop (cdr lst)))
                                              #;(let-values (((ht) '#hash()))
                                                  (let-values (((start) 0)
                                                               ((end) 37)
                                                               ((inc) 1))
                                                    ((letrec-values (((for-loop)
                                                                      (lambda (ht pos)
                                                                        (if (< pos end)
                                                                            (let-values (((j) pos))
                                                                              (let-values (((ht)
                                                                                            (let-values (((ht) ht))
                                                                                              (let-values (((ht) (hash-set ht (loop (cdr lst)) 'a)))
                                                                                                (values ht)))))
                                                                                (for-loop ht (+ pos inc))))
                                                                            ht))))
                                                       for-loop)
                                                     ht
                                                     start)))
                                              (let-values (((l1) (loop (cdr lst))))
                                                (+ 38 l1))))))))))))])
      loop) lst)))

)
