# Build workflow testing if the code compiles.

name: Build

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches:
            - "master"
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up PyPy 2.7
              uses: actions/setup-python@v5
              with:
                python-version: "pypy-2.7-v7.3.17"

            - name: Setup PyPy Code
              run: cd pycket && git clone https://github.com/pypy/pypy.git

            - name: install dependencies
              run: |
                  sudo apt install libffi-dev pkg-config zlib1g-dev libbz2-dev libsqlite3-dev libncurses5-dev libexpat1-dev libssl-dev libgdbm-dev tk-dev libgc-dev liblzma-dev libncursesw5-dev patchelf
                  cd pycket/pypy && pypy -m pip install -r requirements.txt

            - name: Compile Pycket
              run: cd pycket && make pycket-c-linklets