name: Test New Pycket

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches:
            - "master"
env:
  HOME: /home/runner
  PLTHOME: /home/runner/work/pycket/pycket

jobs:
    test-new:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up PyPy 2.7
              uses: actions/setup-python@v5
              with:
                python-version: "pypy-2.7-v7.3.17"

            - name: Setup PyPy Code
              run: git clone https://github.com/pypy/pypy.git

            - name: install dependencies
              run: |
                    sudo apt install libffi-dev pkg-config zlib1g-dev libbz2-dev libsqlite3-dev libncurses5-dev libexpat1-dev libssl-dev libgdbm-dev tk-dev libgc-dev liblzma-dev libncursesw5-dev patchelf
                    pypy -m pip install -r pypy/requirements.txt

            - name: Setup Local Racket
              run: make setup-local-racket

            - name: Run test
              run: |
                mkdir -p $HOME/.config/racket
                make test-new