name: Test Pycket with Racket binary and old expander

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches:
            - "master"
    workflow_run:
        workflows: [Build]
        types: [completed]
jobs:
    on-success:
        name: Test with Linklets
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup PyPy
              run: make setup-pypy
            - name: Setup local Racket
              run: make setup-local-racket
            - name: Run test
              run: make test-old
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
        - run: echo 'Pycket build failed.'